# Generated by Django 5.2 on 2025-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_date_product_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('for_kids', 'For Kids'), ('for_men', 'For Men'), ('for_women', 'For women')], max_length=121),
        ),
    ]
