# Generated by Django 5.2 on 2025-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_published_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('for_kids', 'For Kids'), ('for_men', 'For Men'), ('for_women', 'For women')], max_length=121, null=True),
        ),
    ]
